"""Add missing verification tokens table

Revision ID: 35d5358f2539
Revises: c9d8e7f6a5b4
Create Date: 2026-05-02 10:54:48.279764

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "35d5358f2539"
down_revision: Union[str, None] = "c9d8e7f6a5b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_verification_tokens",
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("exp", sa.BigInteger(), nullable=False),
        sa.Column("used", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("token"),
    )
    op.alter_column(
        "ip_rate_limit_attempts",
        "created_at",
        existing_type=sa.BIGINT(),
        nullable=False,
    )
    op.alter_column(
        "ip_rate_limit_attempts",
        "expires_at",
        existing_type=sa.BIGINT(),
        nullable=False,
    )
    op.alter_column(
        "login_attempts", "created_at", existing_type=sa.BIGINT(), nullable=False
    )
    op.alter_column(
        "login_attempts", "expires_at", existing_type=sa.BIGINT(), nullable=False
    )
    op.alter_column(
        "refresh_tokens", "created_at", existing_type=sa.BIGINT(), nullable=False
    )
    op.alter_column(
        "refresh_tokens", "expires_at", existing_type=sa.BIGINT(), nullable=False
    )
    op.add_column("users", sa.Column("email_verified", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email_verified")
    op.alter_column(
        "refresh_tokens", "expires_at", existing_type=sa.BIGINT(), nullable=True
    )
    op.alter_column(
        "refresh_tokens", "created_at", existing_type=sa.BIGINT(), nullable=True
    )
    op.alter_column(
        "login_attempts", "expires_at", existing_type=sa.BIGINT(), nullable=True
    )
    op.alter_column(
        "login_attempts", "created_at", existing_type=sa.BIGINT(), nullable=True
    )
    op.alter_column(
        "ip_rate_limit_attempts", "expires_at", existing_type=sa.BIGINT(), nullable=True
    )
    op.alter_column(
        "ip_rate_limit_attempts", "created_at", existing_type=sa.BIGINT(), nullable=True
    )
    op.drop_table("email_verification_tokens")
    # ### end Alembic commands ###
